# Generated by Django 4.0 on 2022-01-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_ball', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_cell',
            field=models.CharField(default=123, max_length=30),
        ),
        migrations.AddField(
            model_name='player',
            name='player_email',
            field=models.CharField(default=123, max_length=30),
        ),
    ]
