# Generated by Django 4.0 on 2022-01-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_ball', '0005_alter_player_player_cell_alter_player_player_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_full_text_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name_full_text', models.CharField(max_length=30)),
                ('player_cell_full_text', models.CharField(max_length=30)),
            ],
        ),
    ]
