# Generated by Django 4.0 on 2022-08-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_ball', '0006_player_full_text_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_off', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='player_cell',
            field=models.CharField(max_length=10),
        ),
    ]
