# Generated by Django 4.0 on 2022-08-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_ball', '0007_turnoff_alter_player_player_cell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnoff',
            name='on_off',
            field=models.BooleanField(default=False),
        ),
    ]
