# Generated by Django 4.0 on 2022-08-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_ball', '0008_alter_turnoff_on_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnoff',
            name='flag',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
